### ISSUE TITLE
some more unitialized variables

### ISSUE THREAD

**Issue by chenze42** [oguyon/PIAACMCdesign#10]
Local variable 'bestval' in PIAACMCsimul_exec is still not initialized
before it is printed into linoptval.txt. 'xsize' further up in same file
(line 3173) is similarly uninitialized before printing to stdout, in this
path through the code.

In linopt_imtools.c, line 1700 there is
    double *params;
but then
    params[0] = 0.0;

This is very dangerously zeroing an arbitrary memory location, since
params is not set. The uninitialized 'params' is also sent to linopt_imtools_opt_f(),
but currently not used there. Finally, the address of params is used to
initialize a field of gsl_multimin_function_fdf, which is almost
certainly not what you want.
    opt_func.params = &params;

At COREMOD_memory.c line 5548:

```
pthread_t thread_savefits = (pthread_t) 0;
```

this is nonportable/dangerous as pthread_t is opaque.
Of more concern, further down this function there is
    pthread_join(thread_savefits, (void**)&thread_savefits);
which is a dangerous cast that might overwrite arbitrary
memory through the double indirect. Why not use NULL?

**Comment by oguyon** [comment]
fixed in release 1.2.21
