### ISSUE TITLE
extraneous cruft in 1.2.19

### ISSUE THREAD

**Issue by chenze42** [oguyon/PIAACMCdesign#11]
v1.2.19 won't compile until you remove some unresolved merge goop
from {image_basic.c, linopt_imtool.c, COREMOD_memory.c,
COREMOD_tools.c, and CLIcore.c}. Stuff like
<<<<<<< HEAD

> > > > > > > fe7a8188093e7045b16e32f1091bd4e218b1aaa0

**Comment by oguyon** [comment]
fixed in 1.2.22
