### ISSUE TITLE
save_fits_atomic crashes with core dump

### ISSUE THREAD

**Issue by stevepur** [oguyon/PIAACMCdesign#12]
Line 1440 in COREMOD_iofits.c is incorrect, causing a core dump:
        sprintf("mv %s %s", fnametmp, file_name);
should be
        sprintf(command, "mv %s %s", fnametmp, file_name);

I'll test this fix overnight tonight.

**Comment by stevepur** [comment]
Implementing the above fix results in the tmux child threads giving the following error:
Saving FPMresp (ID = 35) as "piaacmcconf_i000/FPMresp1_s2_l0565_sr10_nbr032_mr200_ccnbr000_ccz002000_ocr0800_ocz000000_ssr50_ssm0_Mirror_wb10_mp04_thread00.fits" ...creating file "!_savefits_atomic_FPMresp.tmp.fits"
mv: rename !_savefits_atomic_FPMresp.tmp.fits to piaacmcconf_i000/FPMresp1_s2_l0565_sr10_nbr032_mr200_ccnbr000_ccz002000_ocr0800_ocz000000_ssr50_ssm0_Mirror_wb10_mp04_thread00.fits: No such file or directory

I found the file _savefits_atomic_FPMresp.tmp.fits in the working directory (not piaacmcconf_i000).  It looks like the fnametmp should not contain the "!", while the name passed to save___fits should.  Testing with the following change:
    sprintf(fnametmp, "_savefits_atomic_%s.tmp.fits", ID_name);
    sprintf(savename, "!%s", fnametmp);
where "savename" is the name passed to save___fits.

**Comment by stevepur** [comment]
I'm concerned about this being thread safe.  Isn't there a danger of multiple threads writing to _savefits_atomic_FPMresp.tmp.fits at the same time?  I'm adding thread number to the temp filename, which implies changes to the save_fits_atomic signature.

**Comment by stevepur** [comment]
How do I turn off markdown?  All I want to do is type plain text.  Markdown is removing characters I type.

**Comment by stevepur** [comment]
I've successfully completed step 100 and am into step 101 with the above fixes.  The performance is excellent, seeing a contrast of 1.45738e-09 compared to 1.5e-7 after three iterations of optsingle 200 with the 2.19 code.  Something else must have gotten fixed.

**Comment by oguyon** [comment]
fixed in release 1.2.25

new function code appends pid and thread id to temporary file name, and fixes the sprintf and "!" bugs:

int save_fits_atomic(char *ID_name, char *file_name)
{
    long ID;
    int atype;
    char fnametmp[1000];
    char savename[1000];
    char command[2000];
    int ret;
    pthread_t self_id;

```
ID = image_ID(ID_name);

self_id=pthread_self();
sprintf(fnametmp, "_savefits_atomic_%s_%d_%ld.tmp.fits", ID_name, (int) getpid(), (unsigned long) self_id);
sprintf(savename, "!%s", fnametmp);
if (ID!=-1)
{
    atype = data.image[ID].md[0].atype;
    switch(atype) {
    case FLOAT:
        save_fl_fits(ID_name, savename);
        break;
    case DOUBLE:
        save_db_fits(ID_name, savename);
        break;
    case USHORT:
        save_sh_fits(ID_name, savename);
        break;
    }

    sprintf(command, "mv %s %s", fnametmp, file_name);
    ret = system(command);
}

return 0;
```

}

**Comment by oguyon** [comment]
check:
https://guides.github.com/features/mastering-markdown/

**Comment by stevepur** [comment]
I don’t want to master markdown.  I want the plain text I copied to be properly formatted when I paste it in a comment without having to type any extra characters.  Imposing markdown in a comment context without it being asked for is absurd.
