### ISSUE TITLE
Fix scope issue that causes OS X to crash

### ISSUE THREAD

**Issue by stevepur** [oguyon/PIAACMCdesign#2]
The current code base has globals defined in .h files, which causes duplicate symbol errors in the OS X version of gcc.  Here is a recommended fix:
1) Move the following globals to CLIcore.c:
pid_t CLIPID;
char DocDir[200];       // location of documentation
char SrcDir[200];       // location of source
char BuildFile[200];    // file name for source
char BuildDate[200];
char BuildTime[200];

uid_t euid_real;
uid_t euid_called;
uid_t suid;

int TYPESIZE[9];

int C_ERRNO;

2) add "extern" to the declaration of these globals in CLIcore.h
extern pid_t CLIPID;
extern char DocDir[200];        // location of documentation
extern char SrcDir[200];        // location of source
extern char BuildFile[200]; // file name for source
extern char BuildDate[200];
extern char BuildTime[200];

extern int C_ERRNO;         // C errno (from errno.h)

…
extern uid_t euid_real;
extern uid_t euid_called;
extern uid_t suid;

…

extern int TYPESIZE[9];

**Comment by oguyon** [comment]
fixed in release 1.2.05
