### ISSUE TITLE
Other scope issues that are a problem on OS X

### ISSUE THREAD

**Issue by stevepur** [oguyon/PIAACMCdesign#3]
There are two other globals that cause duplicate symbol errors on OS X's gcc.  The solutions below are somewhat arbitrary but work.
1) in COREMOD_arith.c, and COREMOD_memory.c, change 
char errmsg[SBUFFERSIZE];
to 
extern char errmsg[SBUFFERSIZE];
which leaves the actual declaration in image_basic.c

2) in COREMOD_iofits.c, change
char errormessage[SBUFFERSIZE];
to 
extern char errormessage[SBUFFERSIZE];
which leaves the actual declaration in an external library routine.

Alternatively, these globals could be given unique names in their files.

**Comment by oguyon** [comment]
fixed in version 1.2.05
