### ISSUE TITLE
multiple clock_gettime declarations cause duplicate symbol errors in OS X

### ISSUE THREAD

**Issue by stevepur** [oguyon/PIAACMCdesign#4]
The easiest solution is to declare all declarations of clock_gettime static in CLIcore.c, fft.c, COREMOD_memory.c, cudacomp.c, linopt_imtools.c, and COREMOD_tools.c.
In each file, change
int clock_gettime(int clk_id, struct timespec *t){
to 
static int clock_gettime(int clk_id, struct timespec *t){

**Comment by oguyon** [comment]
fixed in release 1.2.05
