### ISSUE TITLE
Freeing of uninitialized pointers in PIAACMCsimul.c

### ISSUE THREAD

**Issue by stevepur** [oguyon/PIAACMCdesign#6]
From Chris: In the master branch, could you please remove lines {1604,1605}
and{1954,1955}from PIAACMCsimul.c :

...
1604:    double *piaar0;
1605:    double *piaar1;
...
1954:    free(piaar0);
1955:    free(piaar1);
...

These stack variables are never used. They are never initialized either,
so the free is directed at random memory, which just produced some
really nasty behavior that took a little bit of sorting out.

**Comment by oguyon** [comment]
fixed in v 1.2.18
Thanks for pointing this out
