### ISSUE TITLE
A risky race condition in COREMOD_memory.c

### ISSUE THREAD

**Issue by stevepur** [oguyon/PIAACMCdesign#7]
From Chris: Here's a racy bug:

In COREMOD_memory.c, line 1547

```
   # ifdef _OPENMP
   #pragma omp atomic 
   #endif
   ID = next_avail_image_ID();

   data.image[ID].used = 1;
```

The 'atomic' is irrelevant, since ID is on the calling thread's
stack. (It is also illegal - needs to be 'atomic write'.)

However, the real problem is in next_avail_image_ID():

long next_avail_image_ID() /\* next available ID number */
{
   long i;
   long ID = -1;
   int found = 0;
# ifdef _OPENMP

   #pragma omp critical
   {
# endif

```
   for (i=0; i<data.NB_MAX_IMAGE; i++)
   {
       if((data.image[i].used == 0)&&(found == 0))
       {
           ID = i;
           found = 1;
       }
   }
```
# ifdef _OPENMP

   }
# endif

   if(ID==-1)
       ID = data.NB_MAX_IMAGE;

   return(ID);
}

The danger here is that the critical section is left before
data.image[ID].used is set, since that is left to the calling
thread, so multiple threads could get the same ID. Putting
the update inside the critical section (and adding a break
so it doesn't traverse the loop NB_MAX_IMAGE (=5000)
times) avoids the race.
# ifdef _OPENMP

   #pragma omp critical
   {
# endif

```
   for (i=0; i<data.NB_MAX_IMAGE; i++)
   {
       if ( data.image[i].used == 0 ) 
       {
           ID = i;
           data.image[ID].used = 1;
           break;
       }
   }
```
# ifdef _OPENMP

   }
# endif

The 'atomic' and 'data.image[ID].used = 1;' should be removed
from the callers - the one mentioned up top, and another at
line 2141 (which doesn't have an 'atomic' to begin with).

Bad things are going to happen if data.NB_MAX_IMAGE is
ever returned.

**Comment by oguyon** [comment]
Thanks for pointing this out.
Fixed in v 1.2.18

Having no quick clean solution to the "reach end of loop" case where NB_MAX_IMAGE is reached, I added a clean exit if this occurs, along with an error message to the user: "increase NB_MAX_IMAGE"
